name: product_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - google-generativeai
  - gspread
  - gspread-dataframe
  - google-auth-oauthlib
  - google-api-python-client
  - grpcio
  - protobuf